### ISSUE TITLE
`Ceph` relation change

### ISSUE THREAD

**Issue by mkalcok** [mkalcok/charm-ceph-csi#4]
Charm should handle when data in ceph relation changes, this would handle use cases when new `ceph-mon` units are added, but also when `ceph-csi` charm is related with `ceph-mon` that is not fully deployed yet and does not contain proper information.

**Comment by auria** [comment]
A use case is when operations teams want to relocate ceph-mon units in different machines. Juju's approach is to add a new unit (within the new machine) and remove an old unit. When this happens, ceph-mon IPs need to get updated on the ceph-csi config.

**Comment by auria** [comment]
Tracking this bug via https://bugs.launchpad.net/charm-ceph-csi/+bug/1940918

**Comment by mkalcok** [comment]
Solved by #16
